FROM node:20.10.0

RUN apt-get clean && apt-get update  && \
    apt-get -y --no-install-recommends  install \
	   npm


WORKDIR /project

COPY ./project /project/

RUN npm i

#  stop next collecting telemetry

ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD ["npm", "run", "dev"]

