services:


  backend:
    restart: unless-stopped
    command: ["python", "run_dev.py"]
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./backend/project:/project/
    ports:
      - 8000:5000
    networks:
      - internal_network
  frontend:
    restart: unless-stopped
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    volumes:
      - ./frontend/project:/project
    ports:
      - 3000:3000
    networks:
      - internal_network
  db: 
    restart: unless-stopped
    image: postgres:16.1
    container_name: database
    healthcheck:
        test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'postgres']
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
       POSTGRES_USER: postgres # SET USING ENV FILE IN PROD
       POSTGRES_PASSWORD: postgres # SET USING ENV FILE IN PROD
       POSTGRES_DB: postgres # SET USING ENV FILE IN PROD
    networks:
      - internal_network
volumes: 
  database: 
  


networks:
    internal_network:
          driver: bridge
          

      